#
version: "1"
services:
  bot:
    container_name: "MemeFiBot"
    build:
      context: .
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python3 main.py -a 2"
    volumes:
      - .:/app
      - ./sessions:/app/sessions
    env_file:
      - .env
